# Generated by Django 4.2.5 on 2023-09-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="picture",
            field=models.CharField(default=""),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="facebook",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="instructor",
            name="website",
            field=models.CharField(blank=True, default="", max_length=100, null=True),
        ),
    ]
